
INSERT INTO [dbo].[Plants] ( [Location], [Light], [GrowthSpeed], [Hight], [Description], [PlantName], [Usage], [Coloration], [Сomplexity], [Area], [OriginCountry], [Type], [SpeciesId], [Family_Id], [Purchase_Id], [MinTemp], [MaxTemp], [MinPh], [MaxPh], [MinGh], [MaxGh])
                           VALUES ( N'Back', N'hight', N'hight', 40, N'Description1', N'Plant_1', N'Aquascape', N'red', N'difficult', N'surface', N'Afrika', N'Type_1',	1, NULL, 7, 21, 27, CAST(6.50 AS Decimal(18, 2)), CAST(7.20 AS Decimal(18, 2)), CAST(1.40 AS Decimal(18, 2)), CAST(16.50 AS Decimal(18, 2)))
INSERT INTO [dbo].[Plants] ( [Location], [Light], [GrowthSpeed], [Hight], [Description], [PlantName], [Usage], [Coloration], [Сomplexity], [Area], [OriginCountry], [Type], [SpeciesId], [Family_Id], [Purchase_Id], [MinTemp], [MaxTemp], [MinPh], [MaxPh], [MinGh], [MaxGh])
                           VALUES ( N'Front', N'low', N'low', 76, N'Description2', N'Test_1', N'home aqua', N'green', N'difficult', N'water', N'India', N'Type_2',		2, NULL, 27, 23, 28, CAST(5.50 AS Decimal(18, 2)), CAST(17.20 AS Decimal(18, 2)), CAST(7.10 AS Decimal(18, 2)), CAST(9.30 AS Decimal(18, 2)))
INSERT INTO [dbo].[Plants] ( [Location], [Light], [GrowthSpeed], [Hight], [Description], [PlantName], [Usage], [Coloration], [Сomplexity], [Area], [OriginCountry], [Type], [SpeciesId], [Family_Id], [Purchase_Id], [MinTemp], [MaxTemp], [MinPh], [MaxPh], [MinGh], [MaxGh])
                           VALUES ( N'Middle', N'hight', N'hight', 33, N'Description3', N'Name_1', N'Miniaqua', N'blue', N'middle', N'surface', N'Ukraine', N'Type_4',	2, NULL, 29, 20, 30, CAST(3.50 AS Decimal(18, 2)), CAST(10.50 AS Decimal(18, 2)), CAST(2.40 AS Decimal(18, 2)), CAST(4.50 AS Decimal(18, 2)))
INSERT INTO [dbo].[Plants] ( [Location], [Light], [GrowthSpeed], [Hight], [Description], [PlantName], [Usage], [Coloration], [Сomplexity], [Area], [OriginCountry], [Type], [SpeciesId], [Family_Id], [Purchase_Id], [MinTemp], [MaxTemp], [MinPh], [MaxPh], [MinGh], [MaxGh])
                           VALUES ( N'Back', N'middle', N'low', 50, N'Description5', N'SomeName_1', N'Aquascape', N'yellow', N'easie', N'water', N'Afrika', N'Type_2',	1, NULL, 30, 10, 22, CAST(7.50 AS Decimal(18, 2)), CAST(12.70 AS Decimal(18, 2)), CAST(13.40 AS Decimal(18, 2)), CAST(26.40 AS Decimal(18, 2)))
INSERT INTO [dbo].[Plants] ( [Location], [Light], [GrowthSpeed], [Hight], [Description], [PlantName], [Usage], [Coloration], [Сomplexity], [Area], [OriginCountry], [Type], [SpeciesId], [Family_Id], [Purchase_Id], [MinTemp], [MaxTemp], [MinPh], [MaxPh], [MinGh], [MaxGh])
                           VALUES ( N'Front', N'hight', N'hight', 10, N'Description5', N'Plant_4', N'Big tank', N'marine', N'difficult', N'water', N'Poland', N'Type_3',	1, NULL, 3, 16, 25, CAST(1.00 AS Decimal(18, 2)), CAST(6.00 AS Decimal(18, 2)), CAST(3.40 AS Decimal(18, 2)), CAST(6.70 AS Decimal(18, 2)))

